erm/erm/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('', include('responses.urls', namespace='responses')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    # path('cv/')
]

# if settings.DEBUG:
#     urlpatterns += static(
#         settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
#     )

erm/responds/urls.py
from django.urls import path
from . import views

app_name = 'responds'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('respond/<int:pk>/', views.respond_info, name='respond_info'),
]

erm/responses/urls.py
from django.urls import path

from .views import (about, contact, index,
                    response_detail, response_list)

from .views import ResponseView, EmployerView

app_name = 'responses'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('responses/', response_list, name='response_list'),
    path('responses/<int:pk>/', response_detail, name='response_detail'),  # возможно, изменить на <int:response_id>
    path('responses/create/', ResponseView.as_view(), name='create_response'),
    path('responses/some/', EmployerView.as_view(), name='create_employer'),
]

erm/templates/includes/footer.html
<p>
  © {{ year }} Copyright <span style="color:red">Ilia</span> Korepanov
</p>

erm/templates/includes/header.html
<nav class="navbar navbar-light" style="background-color: navy">
  <div class="container">
    <div>
      <a href="{% url 'responses:index' %}">The journey of a thousand miles begins with a single... response</a>
    </div>
    <ul>
      <li>
        <a href="{% url 'responses:about' %}">About</a>
      </li>
      <li>
        <a href="{% url 'responses:contact' %}">Contact</a>
      </li>
      <li>
        <a href="{% url 'responses:response_list' %}">My responses</a>
      </li>
      <li>
        <a href="{% url 'responses:create_response' %}">Create response</a>
      </li>
    </ul>
  <div>
</nav>

{% load static %}

<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'responses:index' %}">
      <img src="{% static 'img/fav/favicon.ico' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          {% if user.is_authenticated %}

          {% comment %} <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}" 
              href="{% url 'posts:post_create' %}"
            >
              Новая запись
            </a>
          </li> {% endcomment %}
          
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:password_change_form' %}active{% endif %}" 
              href="{% url 'users:password_change_form' %}"
            >
              Изменить пароль
            </a>
          </li>
          
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}" 
              href="{% url 'users:logout' %}"
            >
              Выйти
            </a>
          </li>
          
          <li>
            Пользователь: {{ user.username }}
          </li>
          
          {% else %}
          
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}" 
              href="{% url 'users:login' %}"
            >
              Login
            </a>
          </li>
          
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}" 
              href="{% url 'users:signup' %}"
            >
              Signup
            </a>
          </li>
          
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </div>
</nav>

erm/templates/includes/respond_header.html
<tr>
  <th>Дата отклика</th>
  <th>Компания</th>
  <th>Позиция</th>
  <th>Версия резюме</th>
  <th>Использовавшийся шаблон</th>
  <th>Сопроводительное письмо</th>
</tr>