erm/erm/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('', include('responses.urls', namespace='responses')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    # path('cv/')
]

# if settings.DEBUG:
#     urlpatterns += static(
#         settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
#     )

erm/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
      'login/',
      LoginView.as_view(template_name='users/login.html'),
      name='login'
    ),
    path(
      'logout/',
      LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
    path(
      'password_change/',
      PasswordChangeView.
      as_view(template_name='users/password_change_form.html'),
      name='password_change_form'
    ),
    path(
      'password_change/done/',
      PasswordChangeDoneView.
      as_view(template_name='users/password_change_done.html'),
      name='password_change_done'
    ),
    path(
      'password_reset/',
      PasswordResetView.
      as_view(template_name='users/password_reset_form.html'),
      name='password_reset_form'
    ),
    path(
      'password_reset/done/',
      PasswordResetDoneView.
      as_view(template_name='users/password_reset_done.html'),
      name='password_reset_done'
    ),
    path(
      'reset/done/',
      PasswordResetCompleteView.
      as_view(template_name='users/password_reset_complete.html'),
      name='password_reset_complete'
    ),
    path(
      'reset/<uidb64>/<token>/',
      PasswordResetConfirmView.
      as_view(template_name='users/password_reset_confirm.html'),
      name='password_reset_confirm'
    ),
]

erm/responses/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Employer(models.Model):
    """Данные о потенциальном работодателе."""
    name = models.CharField(
        unique=True,
        max_length=100,
        verbose_name='Компания',
        help_text='Укажите название компании-работодателя',
    )
    website = models.URLField(
        unique=True,
        blank=True,
        null=True,
        verbose_name='Сайт',
        help_text='Введите название сайта',
    )

    class Meta:
        ordering = ['name']
        verbose_name = 'Работодатель'
        verbose_name_plural = 'Работодатели'

    def __str__(self):
        return f'{self.name}'


class Agency(models.Model):
    """Данные о кадровом агентстве."""
    name = models.CharField(
        unique=True,
        max_length=100,
        verbose_name='Агентство',
        help_text='Укажите название кадрового агентства',
    )
    website = models.URLField(
        unique=True,
        blank=True,
        null=True,
        verbose_name='Сайт',
        help_text='Введите название сайта',
    )

    class Meta:
        ordering = ['name']
        verbose_name = 'Агентство'
        verbose_name_plural = 'Агентства'

    def __str__(self):
        return f'{self.name}'


class Contact(models.Model):
    """
    Данные о контактном лице в компании-работодателе или кадровом агентстве.
    """
    first_name = models.CharField(
        max_length=100,
        verbose_name='Имя',
        help_text='Укажите имя контактного лица',
    )
    last_name = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name='Фамилия',
        help_text='Укажите фамилию контактного лица',
    )
    role = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name='Должность',
        help_text='Укажите должность контактного лица',
    )
    phone = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        verbose_name='Телефон',
        help_text='Укажите телефон контактного лица',
    )
    email = models.EmailField(
        blank=True,
        null=True,
        verbose_name='E-mail',
        help_text='Укажите E-mail контактного лица',
    )
    telegram = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name='Telegram',
        help_text='Укажите телеграм контактного лица',
    )
    company = models.ForeignKey(
        Employer,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='contacts',
        verbose_name='Компания',
        help_text=('Укажите компанию, которую представляет данное контактное '
                   'лицо'),
    )
    agency = models.ForeignKey(
        Agency,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='contacts',
        verbose_name='Агентство',
        help_text=('Укажите кадровое агентство, которое представляет данное '
                   'контактное лицо'),
    )

    class Meta:
        ordering = ['last_name', 'first_name']
        constraints = [
            models.UniqueConstraint(
                fields=['first_name',
                        'last_name',
                        'phone'],
                name='unique_person_phone',
            ),
            models.UniqueConstraint(
                fields=['first_name',
                        'last_name',
                        'email'],
                name='unique_person_email',
            ),
            models.UniqueConstraint(
                fields=['first_name',
                        'last_name',
                        'telegram'],
                name='unique_person_telegram',
            )
        ]
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        if self.last_name:
            return f'{self.first_name} {self.last_name}'
        return f'{self.first_name}'


class Response(models.Model):
    """Данные об откликах на те или иные вакансии."""
    user = models.ForeignKey(
        User,
        # auto_now_add=True,
        on_delete=models.CASCADE,
        related_name='responses',
        verbose_name='Автор',
    )
    employer = models.ForeignKey(
        Employer,
        on_delete=models.CASCADE,
        related_name='responses',
        verbose_name='Работодатель',
        help_text='Укажите компанию-работодателя',
    )
    agency = models.ForeignKey(
        Agency,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='responses',
        verbose_name='Агентство',
        help_text='Укажите кадровое агентство',
    )
    position = models.CharField(
        max_length=100,
        verbose_name='Вакансия',
        help_text='Укажите вакансию',
    )
    link = models.URLField(
        blank=True,
        null=True,
        verbose_name='Ссылка',
        help_text='Укажите ссылку на вакансию',
    )
    contacts = models.ManyToManyField(
        Contact,
        blank=True,
        related_name='responses',
        verbose_name='Контакты',
        help_text='Укажите контакты по вакансии',
    )
    cv = models.FileField(
        upload_to='cv/',
        blank=True,
        null=True,
        verbose_name='Резюме',
        help_text='Приложите файл резюме',
        )
    letter = models.TextField(
        default='No',
        blank=True,
        null=True,
        verbose_name='Сопроводительное',
        help_text='Напишите сопроводительное письмо',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Создан',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Отредактирован',
    )
    notes = models.TextField(
        blank=True,
        null=True,
        verbose_name='Заметки',
        help_text='Оставьте любые заметки здесь',
    )
    OTPRAVLEN = 'OTP'
    OTKAZ = 'OTK'
    IGNOR = 'IGN'
    TESTOVOE = 'TES'
    INTHR = 'INH'
    INTTL = 'INT'
    INBOSS = 'INB'
    OFFER = 'OFF'
    STATUS_CHOICES = [
        (OTPRAVLEN, 'Отклик'),
        (OTKAZ, 'Отказ'),
        (IGNOR, 'Игнор'),
        (TESTOVOE, 'Тестовое'),
        (INTHR, 'Интервью с HR'),
        (INTTL, 'Интервью с тимлидом'),
        (INBOSS, 'Интервью с вампиром'),
        (OFFER, 'Оффер!'),
    ]
    status = models.CharField(
        max_length=3,
        choices=STATUS_CHOICES,
        default=OTPRAVLEN,
    )

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    def truncated_letter(self):
        return self.letter[:30]

    def __str__(self):
        if self.agency:
            return f'{self.position} в {self.employer} через {self.agency}'
        return f'{self.position} в {self.employer}'

erm/users/models.py
from django.db import models

# Create your models here.

erm/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

erm/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('responses:index')
    template_name = 'users/signup.html'

erm/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}Вы вышли из системы{% endblock %}

{% block content %}
  <main>
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Выход
          </div>
          <div class="card-body">
            <p>
              Вы вышли из своей учётной записи. Ждём вас снова! Ура!
              Не грустите, похрустите!
            </p>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

erm/templates/users/login.html
{% extends "base.html" %}

{% block title %}Войти{% endblock %}

{% load user_filters %}

{% block content %}
  <main>
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Войти на сайт
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post"
                  {% if action_url %}
                    action="{% url action_url %}"
                  {% endif %}
            >
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3"
                     {% if field.field.required %}
                       aria-required="true"
                     {% else %}
                       aria-required="false"
                     {% endif %}
                >
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  <div>
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                        id="{{ field.id_for_label }}-help"
                        class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                    <div>
                    </div>
              {% endfor %}
              <br>
              <div class="col text-center">
                <button type="submit" class="btn btn-primary">
                  Войти
                </button>
                <a
                  href="{% url 'users:password_reset_form' %}"
                  class="btn btn-link"
                >
                  Забыли пароль?
                </a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

erm/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}Пароль изменён{% endblock %}

{% block content%}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Пароль изменён
            </div>
            <div class="card-body">
              <p>Пароль изменён успешно</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

erm/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %}Изменение пароля{% endblock %}

{% block content%}
  <main>
    <div class="container py-5"> 
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Изменить пароль
            </div>
            <div class="card-body">
              {% load user_filters %}
              <form method="post">
              {% csrf_token %}
                {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }} 
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label> 
                    <input 
                      type="password" 
                      name="{{ field.name }}" 
                      autofocus 
                      class="form-control" 
                      required 
                      id="{{ field.id_for_label }}"
                    >
                      {% if field.help_text %}
                        <small 
                          id="{{ field.id_for_label }}-help" 
                          class="form-text text-muted"
                        >
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                {% endfor %}
                <div class="col text-center">
                  <button type="submit" class="btn btn-primary">
                    Изменить пароль
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

erm/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Сброс пароля прошёл успешно{% endblock %}

{% block content%}
  <main>
    <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
  </main>
{% endblock %}

erm/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}Новый пароль{% endblock %}

{% block content%}
  <main>
    {% if validlink %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  {% for field in form %}
                    <div class="form-group row my-3 p-3">
                      <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                      </label>
                      <input
                        type="password"
                        name="{{ field.name }}"
                        autofocus
                        class="form-control"
                        required
                        id="{{ field.id_for_label }}"
                      >
                      {% if field.help_text %}
                        <small
                          id="{{ field.id_for_label }}-help"
                          class="form-text text-muted"
                        >
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                    </div>
                  {% endfor %}
                  <div class="col text-center">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% else %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">Ошибка</div>
            <div class="card-body">
              <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
  </main>
{% endblock %}

erm/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Сброс пароля прошёл успешно{% endblock %}

{% block content%}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Отправлено письмо
            </div>
            <div class="card-body">
              <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

erm/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block title %}Сброс пароля{% endblock %}

{% block content%}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
            </div>
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_email">
                    Адрес электронной почты
                    <span class="required text-danger">*</span>
                  </label>
                  <input
                    type="email"
                    name="email"
                    maxlength="254"
                    class="form-control"
                    required id="id_email"
                  >
                </div>
                <div class="col text-center">
                  <button type="submit" class="btn btn-primary">
                    Сбросить пароль
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

erm/templates/users/signup.html
{% extends "base.html" %}

{% block title %}Зарегистрироваться{% endblock %}

{% load user_filters %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          <form method="post">
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            
            <div class="col text-center">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}