erm/erm/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('', include('responses.urls', namespace='responses')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    # path('cv/')
]

# if settings.DEBUG:
#     urlpatterns += static(
#         settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
#     )

erm/responses/urls.py
from django.urls import path

from .views import (about, contact, index,
                    response_detail, response_list)

from .views import ResponseView, EmployerView

app_name = 'responses'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('responses/', response_list, name='response_list'),
    path('responses/<int:pk>/', response_detail, name='response_detail'),  # возможно, изменить на <int:response_id>
    path('responses/create/', ResponseView.as_view(), name='create_response'),
    path('responses/some/', EmployerView.as_view(), name='create_employer'),
]

erm/responses/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Employer(models.Model):
    """Данные о потенциальном работодателе."""
    name = models.CharField(
        unique=True,
        max_length=100,
        verbose_name='Компания',
        help_text='Укажите название компании-работодателя',
    )
    website = models.URLField(
        unique=True,
        blank=True,
        null=True,
        verbose_name='Сайт',
        help_text='Введите название сайта',
    )

    class Meta:
        ordering = ['name']
        verbose_name = 'Работодатель'
        verbose_name_plural = 'Работодатели'

    def __str__(self):
        return f'{self.name}'


class Agency(models.Model):
    """Данные о кадровом агентстве."""
    name = models.CharField(
        unique=True,
        max_length=100,
        verbose_name='Агентство',
        help_text='Укажите название кадрового агентства',
    )
    website = models.URLField(
        unique=True,
        blank=True,
        null=True,
        verbose_name='Сайт',
        help_text='Введите название сайта',
    )

    class Meta:
        ordering = ['name']
        verbose_name = 'Агентство'
        verbose_name_plural = 'Агентства'

    def __str__(self):
        return f'{self.name}'


class Contact(models.Model):
    """
    Данные о контактном лице в компании-работодателе или кадровом агентстве.
    """
    first_name = models.CharField(
        max_length=100,
        verbose_name='Имя',
        help_text='Укажите имя контактного лица',
    )
    last_name = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name='Фамилия',
        help_text='Укажите фамилию контактного лица',
    )
    role = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name='Должность',
        help_text='Укажите должность контактного лица',
    )
    phone = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        verbose_name='Телефон',
        help_text='Укажите телефон контактного лица',
    )
    email = models.EmailField(
        blank=True,
        null=True,
        verbose_name='E-mail',
        help_text='Укажите E-mail контактного лица',
    )
    telegram = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name='Telegram',
        help_text='Укажите телеграм контактного лица',
    )
    company = models.ForeignKey(
        Employer,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='contacts',
        verbose_name='Компания',
        help_text=('Укажите компанию, которую представляет данное контактное '
                   'лицо'),
    )
    agency = models.ForeignKey(
        Agency,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='contacts',
        verbose_name='Агентство',
        help_text=('Укажите кадровое агентство, которое представляет данное '
                   'контактное лицо'),
    )

    class Meta:
        ordering = ['last_name', 'first_name']
        constraints = [
            models.UniqueConstraint(
                fields=['first_name',
                        'last_name',
                        'phone'],
                name='unique_person_phone',
            ),
            models.UniqueConstraint(
                fields=['first_name',
                        'last_name',
                        'email'],
                name='unique_person_email',
            ),
            models.UniqueConstraint(
                fields=['first_name',
                        'last_name',
                        'telegram'],
                name='unique_person_telegram',
            )
        ]
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        if self.last_name:
            return f'{self.first_name} {self.last_name}'
        return f'{self.first_name}'


class Response(models.Model):
    """Данные об откликах на те или иные вакансии."""
    user = models.ForeignKey(
        User,
        # auto_now_add=True,
        on_delete=models.CASCADE,
        related_name='responses',
        verbose_name='Автор',
    )
    employer = models.ForeignKey(
        Employer,
        on_delete=models.CASCADE,
        related_name='responses',
        verbose_name='Работодатель',
        help_text='Укажите компанию-работодателя',
    )
    agency = models.ForeignKey(
        Agency,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='responses',
        verbose_name='Агентство',
        help_text='Укажите кадровое агентство',
    )
    position = models.CharField(
        max_length=100,
        verbose_name='Вакансия',
        help_text='Укажите вакансию',
    )
    link = models.URLField(
        blank=True,
        null=True,
        verbose_name='Ссылка',
        help_text='Укажите ссылку на вакансию',
    )
    contacts = models.ManyToManyField(
        Contact,
        blank=True,
        related_name='responses',
        verbose_name='Контакты',
        help_text='Укажите контакты по вакансии',
    )
    cv = models.FileField(
        upload_to='cv/',
        blank=True,
        null=True,
        verbose_name='Резюме',
        help_text='Приложите файл резюме',
        )
    letter = models.TextField(
        default='No',
        blank=True,
        null=True,
        verbose_name='Сопроводительное',
        help_text='Напишите сопроводительное письмо',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Создан',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Отредактирован',
    )
    notes = models.TextField(
        blank=True,
        null=True,
        verbose_name='Заметки',
        help_text='Оставьте любые заметки здесь',
    )
    OTPRAVLEN = 'OTP'
    OTKAZ = 'OTK'
    IGNOR = 'IGN'
    TESTOVOE = 'TES'
    INTHR = 'INH'
    INTTL = 'INT'
    INBOSS = 'INB'
    OFFER = 'OFF'
    STATUS_CHOICES = [
        (OTPRAVLEN, 'Отклик'),
        (OTKAZ, 'Отказ'),
        (IGNOR, 'Игнор'),
        (TESTOVOE, 'Тестовое'),
        (INTHR, 'Интервью с HR'),
        (INTTL, 'Интервью с тимлидом'),
        (INBOSS, 'Интервью с вампиром'),
        (OFFER, 'Оффер!'),
    ]
    status = models.CharField(
        max_length=3,
        choices=STATUS_CHOICES,
        default=OTPRAVLEN,
    )

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    def truncated_letter(self):
        return self.letter[:30]

    def __str__(self):
        if self.agency:
            return f'{self.position} в {self.employer} через {self.agency}'
        return f'{self.position} в {self.employer}'

erm/responses/forms.py
from django import forms
from .models import Response, Employer


class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ['user', 'employer', 'position']


class EmployerForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = '__all__'

erm/responses/views.py
from django.shortcuts import get_object_or_404, render, redirect

from erm.settings import NUMBER_OF_RESULT_ENTRIES

from .models import Response

# from django.core.paginator import Paginator

from django.contrib.auth.decorators import login_required

from django.views.generic.edit import CreateView
from .forms import ResponseForm, EmployerForm

from django.urls import reverse_lazy


def index(request):
    # responses = Response.objects.all()[:NUMBER_OF_RESULT_ENTRIES]
    title = 'Ваши отклики'
    context = {
        'title': title,
        # 'responses': responses,
    }
    return render(request, 'responses/index.html', context)

# def paginator(request, responses):
#     paginator = Paginator(responses, NUMBER_OF_RESULT_ENTRIES)
#     page_number = request.GET.get('page')
#     return paginator.get_page(page_number)


# def index(request):
#     responses = Response.objects.all()
#     page_obj = paginator(request, responses)
#     context = {
#         'page_obj': page_obj,
#     }
#     return render(request, 'responses/index.html', context)


def about(request):
    title = 'Об авторе проекта'
    context = {
        'title': title,
    }
    return render(request, 'responses/about.html', context)


def contact(request):
    title = 'Контакты'
    context = {
        'title': title,
    }
    return render(request, 'responses/contact.html', context)


# @login_required
# def application_list(request):
#     applications = JobApplication.objects.filter(user=request.user)
#     return render(request, 'responses/application_list.html', {'applications': applications})


# @login_required
# def create_application(request):
#     if request.method == 'POST':
#         form = JobApplicationForm(request.POST, request.FILES)
#         if form.is_valid():
#             application = form.save(commit=False)
#             application.user = request.user
#             application.save()
#             return redirect('application_list')
#     else:
#         form = JobApplicationForm()
#     return render(request, 'responses/create_application.html', {'form': form})


@login_required
def response_list(request):
    title = 'Мои отклики'
    responses = (Response.objects.prefetch_related('user',
                                                   'employer',
                                                   'agency',
                                                   'contacts')
                                 .all())
                                #  .order_by('-date')[:2])
                                #  .order_by('-date'))
    context = {
        'title': title,
        'responses': responses,
    }
    return render(request, 'responses/response_list.html', context)


@login_required
def response_detail(request, pk):
    title = f'Отклик №{pk}'
    response = get_object_or_404(Response, pk=pk)
    context = {
        'title': title,
        'response': response,
    }
    return render(request, 'responses/response_detail.html', context)


# @login_required
# def create_response(request):
#     title = 'Создать отклик'
#     context = {
#         'title': title,
#     }
#     return render(request, 'responses/create_response.html', context)


class ResponseView(CreateView):
    form_class = ResponseForm
    template_name = 'responses/create_response.html'
    success_url = reverse_lazy('responses:response_list')


class EmployerView(CreateView):
    form_class = EmployerForm
    template_name = 'responses/create_employer.html'
    success_url = reverse_lazy('responses:about')

erm/templates/responses/about.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        Content from about
      </div>
    </div>
  </div>
{% endblock %}

erm/templates/responses/application_list.html
{% extends 'base.html' %}

{% block title %}
  Application_list
{% endblock %}

{% block content%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        Content from application_list
      </div>
    </div>
  </div>
{% endblock %}

erm/templates/responses/contact.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        Content from contact
      </div>
    </div>
  </div>
{% endblock %}

erm/templates/responses/create_application.html
{% extends 'base.html' %}

{% block title %}
  Create_application
{% endblock %}

{% block content%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        Content from create_application
      </div>
    </div>
  </div>
{% endblock %}

erm/templates/responses/create_employer.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <!-- Content from create_employer -->
        <form method="post" action="{% url 'responses:create_employer' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Отправить">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

erm/templates/responses/create_response.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <!-- Content from create_response -->
        <form method="post" action="{% url 'responses:create_response' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Отправить">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

erm/templates/responses/response_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <h1>
          Отклик {{ response.pk }}
        </h1>
        <ul>
          <li>
            {{ response.user }}
          </li>
          <li>
            {{ response.date }}
          </li>
          <li>
            {{ response.employer }}
          </li>
          <li>
            {{ response.position }}
          </li>
          <li>
            {{ response.employercontact }}
          </li>
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

erm/templates/responses/response_info.html
{% extends 'base.html' %}

{% block title %}
  Response {{ response.pk }}
{% endblock %}

{% block content%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <p>
          Content from respond_info about respond {{ response.pk }}
        </p>
        <div>
          <ul class="hr">
            <li>
              Дата отклика: {{ response.resp_date|date:"d M Y" }}
            </li>
            <li>
              Компания: {{ response.company }}
            </li>
            <li>
              Позиция: {{ response.position }}
            </li>
            <li>
              Версия резюме: {{ response.cv }}
            </li>
            <li>
              Использовавшийся шаблон: {{ response.template }}
            </li>
            <li>
              Сопроводительное письмо: {{ response.letter }}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

erm/templates/responses/response_list.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <ol>
          {% for response in responses %}
            <li>
              <ul>
                <li>
                  {{ response.user }}
                </li>
                <li>
                  {{ response.employer }}
                </li>
                {% if response.agency %}
                  <li>
                    {{ response.agency }}
                  </li>
                {% endif %}
                <li>
                  {{ response.position }}
                </li>
                <li>
                  {{ response.link }}
                </li>
                <li>
                  {{ response.contacts }}
                </li>
                <li>
                  {{ response.cv }}
                </li>
                <li>
                  {{ response.letter }}
                </li>
                <li>
                  {{ response.created_at }}
                </li>
                <li>
                  {{ response.updated_at }}
                </li>
                <li>
                  {{ response.note }}
                </li>
                <a href="{% url 'responses:response_detail' response.pk %}">
                  <button type="button" class="btn btn-primary">Подробнее</button>
                </a>
              </ul>
            </li>
          {% empty %}
            <p>
              У вас пока нет ни одного отклика. Пора это исправить!
            </p>
          {% endfor %}
        </ol>
      </div>
    </div>
  </div>
{% endblock %}